var rule ={
title: '爽爽短剧',
host: 'https://ssdj.cc',
url: 'https://ssdj.cc/fyclass/page/fypage/',
searchUrl: 'https://ssdj.cc/search/**/page/fypage/',
class_name: '热播&短剧&都市&萌宝&男频&女频&复仇&虐恋&甜宠&逆袭&战神&亲情&古装&穿越&现代言情&重生&强者回归&现实&豪门恩怨',
class_url: 'rebo&dj&tag/都市&tag/萌宝&tag/男频&tag/女频&tag/复仇&tag/虐恋&tag/甜宠&tag/逆袭&tag/战神&tag/亲情&tag/古装&tag/穿越&tag/现代言情&tag/重生&tag/强者回归&tag/现实&tag/豪门恩怨',
searchable: 2,
headers: {'User-Agent': 'MOBILE_UA',},
play_parse: true,
limit: 6,
double: true,
推荐: '.items;.item;h3&&Text;.thumb&&src;.remarks&&Text;a&&href;.tags&&Text',
一级: '.items .item;h3&&Text;.thumb&&src;.remarks&&Text;a&&href;.tags&&Text',
二级: {
    title: 'figcaption&&Text;.info-mark&&Text',
    img: '.text-thumb img&&src',
    desc: '.info-addtime&&Text;.',
content: '.info-detail&&Text',
tabs: '.ep-nav',
lists: '.ep-items:eq(#id)&&a',
},
搜索: '.items .item;h3&&Text;.thumb&&src;.remarks&&Text;a&&href;.tags&&Text',
}